#!/bin/sh

DIR=~/University/COMP9243/Assignments/distributed-shared-memory/Code
PROG=$1

cp $DIR/Examples/$PROG.c $DIR/$PROG.c

gcc $PROG.c sm.c -o $PROG
make
./dsm -n 2 $DIR/$PROG

make clean
rm $PROG $PROG.c